ad  code for HW04-auth
voprim/nodejs-homework-rest-api pull request #3
Opened 2023-02-23 15:14 UTC by voprim

Проверьте, пожалуйста, ДЗ 4.

2023-02-23 22:34 UTC, Harryk13 commented
Не зроблена частина ДЗ по захисту контактів

2023-02-24 09:22 UTC, voprim commented
добавил защиту на контакты

2023-02-24 11:56 UTC, Harryk13 commented on src/routes/api/contactsRouter.js
> +router.get("/", authenticate, async (req, res, next) => {
а як же реалізація в самих методах? Чи то нормально коли будь хто з користувачів може робити все що завгодно з чужими контактами?

2023-02-26 10:43 UTC, voprim commented
добавил проверку ИД пользователя

2023-02-27 13:36 UTC, voprim commented
добавил проверку owner. проверьте, пожалуйста

2023-02-27 16:50 UTC, Harryk13 commented on src/models/contactModel.js
> +    const res = await Contact.find({ $and: [{ owner }, { favorite }] })
раджу почитати документацію https://mongoosejs.com/docs/api.html#model_Model-find, щоб не робити зайве навантаження на БД

2023-02-27 16:50 UTC, Harryk13 commented on src/models/contactModel.js
> +  const result = await Contact.find({ $and: [{ owner }, { _id: contactId }] });
це масив, а вам треба повернути об'єкт, будьте уважні

2023-02-27 16:50 UTC, Harryk13 commented on src/models/contactModel.js
> +  const result = await Contact.find({ $and: [{ owner }, { _id: contactId }] });
і знов таки раджу почитати документацію, не робіть зайвого навантаження на БД

2023-02-27 16:50 UTC, Harryk13 commented on src/models/contactModel.js
> +    $and: [{ owner }, { _id: contactId }],
це так не працює, почитайте документацію

2023-02-27 16:50 UTC, Harryk13 commented on src/models/contactModel.js
> +    { $and: [{ owner }, { _id: contactId }] },
аналогічно, читаємо документацію

2023-03-03 20:39 UTC, voprim commented
Внес изменения. Проверьте, пожалуйста

2023-03-03 21:29 UTC, Harryk13 commented on src/models/contactModel.js
> +      const data = await Contact.find({ owner: id }, "", { skip, limit: Number(limit) }).populate(
а як же фільтрація? Вам треба і фільтрувати і пагінацію робити одночасно, а не то або то

2023-03-03 21:29 UTC, Harryk13 commented on src/models/contactModel.js
> +    const data = await Contact.findByIdAndUpdate(contactId, body, { new: true });
а як же захист по овнеру?

2023-03-03 21:29 UTC, Harryk13 commented on src/controllers/contactsController.js
> +  const contact = await Contacts.removeContact(req.params.contactId);
а як же захист по овнеру?

2023-03-04 11:49 UTC, Eastvarga requested changes
Є багато зауважень

2023-03-04 11:49 UTC, Eastvarga commented on server.js
>      app.listen(PORT);
Погане розуміння промісів та роботи з ними - більше практики потрібно.
Подумайте чому цей код
mongoose
  .connect(process.env.MONGO_URL)
  .then(() => {
    app.listen(PORT,()=>console.log(\`The server lanched on port ${PORT}`));
    console.log("Database connection successful");
  })
  .catch((error) => {
    console.log(error.message);
    process.exit(1);
  });

призводить до такого результату у консолі, зважайте на послідовність
`Database connection successful`
`The server lanched on port 3000`
https://prnt.sc/5xBnTiPeyxNz

2023-03-04 11:49 UTC, Eastvarga commented on src/controllers/contactsController.js
> +};
Код не працює, запит повертає 500 помилку.
Не варто здавати роботу котра не перевірина Вами на прецездатність, якщо щось не розумієте, або не виходить, спілкуйтесь з товаришами по курсу, задайте питання, але не варто здавати непрацюючу роботу мовчки, це погана поведінка, особливо у сфері айті

2023-03-04 11:49 UTC, Eastvarga commented on src/routes/api/contactsRouter.js
>      const contacts = await listContacts();
Невірно.
Не дивує що Ви нічого не передаєте до listContacts()?
жодного з аргументів. Бо це старий ДЗ2 метод. Чому Ви його залишили мені не відомо, але тут не повинна визиватись ця функція, та й взагалі
router.get("/", authenticate, listContacts) повино бути listContacts з contactsControllers. А сам контролер краще обернути у хендлер помилок, у матеріалах приклад повинен бути, попрацюйте з матеріалами мабуть попередніх модулів, будь ласка.
По потоку дій від ДЗ до наступного ДЗ Вам потрібно було модифікувати старий listContacts під роботу з монго схемой - тоб-то стара реалізація повинна була сщезнути залишитись лише реалізація у контроллері contactsControllers. Все що працювало з локальним файлом Джсон повинно було переробитись на працю з монгустом та базою данних

2023-03-04 11:49 UTC, Eastvarga commented on src/routes/api/contactsRouter.js
>      const contacts = await listContacts();
Теж саме по всім раутам контактів, Ви створили контроллери але їх не додали до робочого процесу

router.get("/:contactId", authenticate, isValidId, async (req, res, next) => { ......

а повинно бути
router.get("/:contactId", authenticate, isValidId, getContactById) де getContactById з contactsControllers

2023-03-04 11:49 UTC, Eastvarga commented on src/models/contactModel.js
> +      const data = await Contact.find({ owner: id }, "", { skip, limit: Number(limit) }).populate(
Хм,
за логікою контроллеру який Ви реалізували у Вас не буде варанту коли 
skip || limit - не визначені 
бо у контроллері Ви їх ініціалізуєте значенням за замовченням.
ось
const { _id: id } = req.user;
  const { page = 1, limit = 20, favorite } = req.query;
  const skip = (page - 1) * limit;
Єдине що не чипаєте це favorite та id  але id  теж ініціалізовано попереднім мідлваром авторізації (бо інакше авторізація б відповіла помилкою та код далі не пішов би)

2023-03-04 11:49 UTC, Eastvarga commented on src/models/contactModel.js
> +      const data = await Contact.find({ favorite: favorite }).populate("owner", "_id username email");
Не вірний підхід.
Вам треба в залежності від favorite формувати аргументи для цієї функції
Щось накшталт цього, реалізація стара в новому мангусті може не працювати, Вам добра практика над аналізом коду.
 const { docs: contacts, totalDocs: total } = await Contact.paginate(
    {
      owner: id,
      ...(favorite ? { favorite: favorite } : {})
    },
    {
      // select,
      limit,
      page,
      sort: {
        ...(sortBy ? { [\`${sortBy}\`]: 1 } : {}),
        ...(sortByDesc ? { [\`${sortByDesc}`]: -1 } : {})
      }
      // populate: {
      //   path: 'owner',
      //   select: 'email subscription -_id'
      // }
    }
  )

2023-03-04 11:49 UTC, Eastvarga commented on src/models/contactModel.js
> +const removeContact = async (contactId) => {
невірно, 
зараз, з додаванням авторізації, Ви повинні видаляти тільки ті контакти котрі належать юзеру, котрий сидить у Вас у запиті після мідлвару авторизації. 
Отже шукати повинні один запис по двом параметрам айді запису та айді володаря запису - юзера

2023-03-04 11:49 UTC, Eastvarga commented on src/models/contactModel.js
> +const updateContact = async (contactId, body) => {
теж саме у параметрах функції повинен бути володар-юзер контакту -  Ви повинні оновити контакт якщо у юзера є такий контакт - отже по двом параметрам контакт айді та юзер айді оновлювати треба

2023-03-04 11:49 UTC, Eastvarga commented on src/routes/api/contactsRouter.js
> +router.get("/:contactId", authenticate, isValidId, async (req, res, next) => {
Усі ці контроллери
 async (req, res, next) => {

ви повинні замінити на ті що реалізували у contactsController

2023-04-02 15:45 UTC, closed without merging